#ifndef MICROPY_INCLUDED_SHARED_BINDINGS_PITCH__INIT__H
#define MICROPY_INCLUDED_SHARED_BINDINGS_PITCH__INIT__H

#include "py/obj.h"

// Nothing now.

#endif //MICROPY_INCLUDED_SHARED_BINDINGS_PITCH__INIT__H